ORIGINAL_PATH=$PATH

MYSQL_PLAY_DESTINATION_VERSION=$MYSQL_VERSION
MYSQL_PLAY_SOURCE_NAME=$MYSQL_DB_NAME
MYSQL_PLAY_DESTINATION_NAME=$MYSQL_PLAY_SOURCE_NAME
MYSQL_PLAY_DESTINATION_PORT=$(grep -E '^ *port=' $HOME/workspace/myProjects/config-samples/mysql/$MYSQL_PLAY_DESTINATION_VERSION/$OS/my.cnf | awk -F= '{print $2}' | tr -d ' ')
MYSQL_PLAY_DESTINATION_SOCKET="$HOME/programs/mysql/$MYSQL_PLAY_DESTINATION_VERSION/data/mysql_"$(echo "$MYSQL_PLAY_DESTINATION_VERSION" | sed 's/\./_/g')".sock"
MYSQL_PLAY_DESTINATION_PASSWORD=password
MYSQL_PLAY_DESTINATION_USER=shreyas

export PATH=$HOME/programs/mysql/$MYSQL_PLAY_DESTINATION_VERSION/bin:$ORIGINAL_PATH
printf "Restoring for $MYSQL_PLAY_SOURCE_NAME\n"
mysqladmin -P $MYSQL_PLAY_DESTINATION_PORT -u $MYSQL_PLAY_DESTINATION_USER -p$MYSQL_PLAY_DESTINATION_PASSWORD -S $MYSQL_PLAY_DESTINATION_SOCKET -f drop $MYSQL_PLAY_DESTINATION_NAME > /dev/null 2>&1
mysqladmin -P $MYSQL_PLAY_DESTINATION_PORT -u $MYSQL_PLAY_DESTINATION_USER -p$MYSQL_PLAY_DESTINATION_PASSWORD -S $MYSQL_PLAY_DESTINATION_SOCKET create $MYSQL_PLAY_DESTINATION_NAME > /dev/null 2>&1
#mysql -P $MYSQL_PLAY_DESTINATION_PORT -u $MYSQL_PLAY_DESTINATION_USER -p$MYSQL_PLAY_DESTINATION_PASSWORD $MYSQL_PLAY_DESTINATION_NAME -S $MYSQL_PLAY_DESTINATION_SOCKET < "$HOME/workspace/myProjects/cric-db-backups/$MYSQL_PLAY_SOURCE_NAME.sql" > /dev/null 2>&1
mysql -P $MYSQL_PLAY_DESTINATION_PORT -u $MYSQL_PLAY_DESTINATION_USER -p$MYSQL_PLAY_DESTINATION_PASSWORD $MYSQL_PLAY_DESTINATION_NAME -S $MYSQL_PLAY_DESTINATION_SOCKET < "$HOME/workspace/myProjects/cric-db-backups/$MYSQL_PLAY_SOURCE_NAME.sql"